FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        python3 \
        python3-pip \
        ca-certificates && \
    pip3 install "conan" && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
