var namespaceaxi =
[
    [ "bfm", null, [
      [ "axi4_initiator", "structaxi_1_1bfm_1_1axi4__initiator.html", "structaxi_1_1bfm_1_1axi4__initiator" ],
      [ "axi4_target", "structaxi_1_1bfm_1_1axi4__target.html", "structaxi_1_1bfm_1_1axi4__target" ]
    ] ],
    [ "fsm", null, [
      [ "AckRecv", "structaxi_1_1fsm_1_1AckRecv.html", null ],
      [ "ATrans", "structaxi_1_1fsm_1_1ATrans.html", "structaxi_1_1fsm_1_1ATrans" ],
      [ "AxiProtocolFsm", "structaxi_1_1fsm_1_1AxiProtocolFsm.html", "structaxi_1_1fsm_1_1AxiProtocolFsm" ],
      [ "base", "structaxi_1_1fsm_1_1base.html", "structaxi_1_1fsm_1_1base" ],
      [ "BegPartReq", "structaxi_1_1fsm_1_1BegPartReq.html", null ],
      [ "BegPartResp", "structaxi_1_1fsm_1_1BegPartResp.html", null ],
      [ "BegReq", "structaxi_1_1fsm_1_1BegReq.html", null ],
      [ "BegResp", "structaxi_1_1fsm_1_1BegResp.html", null ],
      [ "EndPartReq", "structaxi_1_1fsm_1_1EndPartReq.html", null ],
      [ "EndPartResp", "structaxi_1_1fsm_1_1EndPartResp.html", null ],
      [ "EndReq", "structaxi_1_1fsm_1_1EndReq.html", null ],
      [ "EndResp", "structaxi_1_1fsm_1_1EndResp.html", null ],
      [ "EndRespNoAck", "structaxi_1_1fsm_1_1EndRespNoAck.html", null ],
      [ "fsm_handle", "structaxi_1_1fsm_1_1fsm__handle.html", "structaxi_1_1fsm_1_1fsm__handle" ],
      [ "Idle", "structaxi_1_1fsm_1_1Idle.html", "structaxi_1_1fsm_1_1Idle" ],
      [ "PartialRequest", "structaxi_1_1fsm_1_1PartialRequest.html", "structaxi_1_1fsm_1_1PartialRequest" ],
      [ "PartialResponse", "structaxi_1_1fsm_1_1PartialResponse.html", "structaxi_1_1fsm_1_1PartialResponse" ],
      [ "ReadIdle", "structaxi_1_1fsm_1_1ReadIdle.html", "structaxi_1_1fsm_1_1ReadIdle" ],
      [ "Request", "structaxi_1_1fsm_1_1Request.html", "structaxi_1_1fsm_1_1Request" ],
      [ "Response", "structaxi_1_1fsm_1_1Response.html", "structaxi_1_1fsm_1_1Response" ],
      [ "WaitAck", "structaxi_1_1fsm_1_1WaitAck.html", "structaxi_1_1fsm_1_1WaitAck" ],
      [ "WaitForResponse", "structaxi_1_1fsm_1_1WaitForResponse.html", "structaxi_1_1fsm_1_1WaitForResponse" ],
      [ "WReq", "structaxi_1_1fsm_1_1WReq.html", null ],
      [ "WriteIdle", "structaxi_1_1fsm_1_1WriteIdle.html", "structaxi_1_1fsm_1_1WriteIdle" ]
    ] ],
    [ "pe", "namespaceaxi_1_1pe.html", "namespaceaxi_1_1pe" ],
    [ "scv", null, [
      [ "impl", null, [
        [ "ace_recording_payload", "classaxi_1_1scv_1_1impl_1_1ace__recording__payload.html", "classaxi_1_1scv_1_1impl_1_1ace__recording__payload" ],
        [ "ace_recording_types", "structaxi_1_1scv_1_1impl_1_1ace__recording__types.html", "structaxi_1_1scv_1_1impl_1_1ace__recording__types" ]
      ] ],
      [ "ace_recorder", "classaxi_1_1scv_1_1ace__recorder.html", "classaxi_1_1scv_1_1ace__recorder" ],
      [ "axi_recorder", "classaxi_1_1scv_1_1axi__recorder.html", "classaxi_1_1scv_1_1axi__recorder" ],
      [ "axitlm_recorder_module", "classaxi_1_1scv_1_1axitlm__recorder__module.html", "classaxi_1_1scv_1_1axitlm__recorder__module" ]
    ] ],
    [ "ace", "structaxi_1_1ace.html", "structaxi_1_1ace" ],
    [ "ace_bw_transport_if", "classaxi_1_1ace__bw__transport__if.html", null ],
    [ "ace_ext_recording", "classaxi_1_1ace__ext__recording.html", null ],
    [ "ace_extension", "structaxi_1_1ace__extension.html", "structaxi_1_1ace__extension" ],
    [ "ace_initiator_socket", "structaxi_1_1ace__initiator__socket.html", "structaxi_1_1ace__initiator__socket" ],
    [ "ace_response", "structaxi_1_1ace__response.html", "structaxi_1_1ace__response" ],
    [ "ace_target_socket", "structaxi_1_1ace__target__socket.html", "structaxi_1_1ace__target__socket" ],
    [ "ar_ch", "structaxi_1_1ar__ch.html", "structaxi_1_1ar__ch" ],
    [ "aw_ch", "structaxi_1_1aw__ch.html", "structaxi_1_1aw__ch" ],
    [ "axi3", "structaxi_1_1axi3.html", "structaxi_1_1axi3" ],
    [ "axi3_ext_recording", "classaxi_1_1axi3__ext__recording.html", null ],
    [ "axi3_extension", "structaxi_1_1axi3__extension.html", "structaxi_1_1axi3__extension" ],
    [ "axi4", "structaxi_1_1axi4.html", "structaxi_1_1axi4" ],
    [ "axi4_ext_recording", "classaxi_1_1axi4__ext__recording.html", null ],
    [ "axi4_extension", "structaxi_1_1axi4__extension.html", "structaxi_1_1axi4__extension" ],
    [ "axi4lite_tlm2pin_adaptor", "classaxi_1_1axi4lite__tlm2pin__adaptor.html", "classaxi_1_1axi4lite__tlm2pin__adaptor" ],
    [ "axi_cfg", "structaxi_1_1axi__cfg.html", "structaxi_1_1axi__cfg" ],
    [ "axi_extension", "structaxi_1_1axi__extension.html", "structaxi_1_1axi__extension" ],
    [ "axi_initiator", "classaxi_1_1axi__initiator.html", "classaxi_1_1axi__initiator" ],
    [ "axi_initiator_base", "classaxi_1_1axi__initiator__base.html", "classaxi_1_1axi__initiator__base" ],
    [ "axi_initiator_socket", "structaxi_1_1axi__initiator__socket.html", "structaxi_1_1axi__initiator__socket" ],
    [ "axi_pin2tlm_adaptor", "classaxi_1_1axi__pin2tlm__adaptor.html", "classaxi_1_1axi__pin2tlm__adaptor" ],
    [ "axi_protocol_types", "structaxi_1_1axi__protocol__types.html", "structaxi_1_1axi__protocol__types" ],
    [ "axi_target", "classaxi_1_1axi__target.html", "classaxi_1_1axi__target" ],
    [ "axi_target_base", "classaxi_1_1axi__target__base.html", "classaxi_1_1axi__target__base" ],
    [ "axi_target_socket", "structaxi_1_1axi__target__socket.html", "structaxi_1_1axi__target__socket" ],
    [ "axi_tlm2pin_adaptor", "classaxi_1_1axi__tlm2pin__adaptor.html", "classaxi_1_1axi__tlm2pin__adaptor" ],
    [ "b_ch", "structaxi_1_1b__ch.html", "structaxi_1_1b__ch" ],
    [ "bw_blocking_transport_if", "classaxi_1_1bw__blocking__transport__if.html", "classaxi_1_1bw__blocking__transport__if" ],
    [ "common", "structaxi_1_1common.html", "structaxi_1_1common" ],
    [ "enable_for_enum", "structaxi_1_1enable__for__enum.html", null ],
    [ "enable_for_enum< bar_e >", "structaxi_1_1enable__for__enum_3_01bar__e_01_4.html", null ],
    [ "enable_for_enum< burst_e >", "structaxi_1_1enable__for__enum_3_01burst__e_01_4.html", null ],
    [ "enable_for_enum< domain_e >", "structaxi_1_1enable__for__enum_3_01domain__e_01_4.html", null ],
    [ "enable_for_enum< lock_e >", "structaxi_1_1enable__for__enum_3_01lock__e_01_4.html", null ],
    [ "enable_for_enum< resp_e >", "structaxi_1_1enable__for__enum_3_01resp__e_01_4.html", null ],
    [ "enable_for_enum< snoop_e >", "structaxi_1_1enable__for__enum_3_01snoop__e_01_4.html", null ],
    [ "master_types", "structaxi_1_1master__types.html", "structaxi_1_1master__types" ],
    [ "request", "structaxi_1_1request.html", "structaxi_1_1request" ],
    [ "response", "structaxi_1_1response.html", "structaxi_1_1response" ],
    [ "rresp_ch", "structaxi_1_1rresp__ch.html", "structaxi_1_1rresp__ch" ],
    [ "select_if", "structaxi_1_1select__if.html", "structaxi_1_1select__if" ],
    [ "select_if< true, T, S >", "structaxi_1_1select__if_3_01true_00_01T_00_01S_01_4.html", "structaxi_1_1select__if_3_01true_00_01T_00_01S_01_4" ],
    [ "signal_types", "structaxi_1_1signal__types.html", "structaxi_1_1signal__types" ],
    [ "slave_types", "structaxi_1_1slave__types.html", "structaxi_1_1slave__types" ],
    [ "wdata_ch", "structaxi_1_1wdata__ch.html", "structaxi_1_1wdata__ch" ]
];