var namespacenonstd_1_1detail =
[
    [ "conjunction", "structnonstd_1_1detail_1_1conjunction.html", null ],
    [ "conjunction&lt; B &gt;", "structnonstd_1_1detail_1_1conjunction_3_01B_01_4.html", null ],
    [ "conjunction&lt; B, Bs... &gt;", "structnonstd_1_1detail_1_1conjunction_3_01B_00_01Bs_8_8_8_01_4.html", null ],
    [ "invoke_result_impl", "structnonstd_1_1detail_1_1invoke__result__impl.html", null ],
    [ "invoke_result_impl&lt; F, decltype(detail::invoke(std::declval&lt; F &gt;(), std::declval&lt; Us &gt;()...), void()), Us... &gt;", "structnonstd_1_1detail_1_1invoke__result__impl_3_01F_00_01decltype_07detail_1_1invoke_07std_1_1d93385ec22a5e390d0b206f42b452de3f.html", null ],
    [ "is_swappable", "structnonstd_1_1detail_1_1is__swappable.html", null ],
    [ "is_swappable&lt; T[N], T[N]&gt;", "structnonstd_1_1detail_1_1is__swappable_3_01T_0fN_0e_00_01T_0fN_0e_4.html", null ],
    [ "is_nothrow_swappable", "structnonstd_1_1detail_1_1is__nothrow__swappable.html", null ],
    [ "voider", "structnonstd_1_1detail_1_1voider.html", null ],
    [ "is_optional_impl", "structnonstd_1_1detail_1_1is__optional__impl.html", null ],
    [ "is_optional_impl&lt; optional&lt; T &gt; &gt;", "structnonstd_1_1detail_1_1is__optional__impl_3_01optional_3_01T_01_4_01_4.html", null ],
    [ "returns_void_impl", "structnonstd_1_1detail_1_1returns__void__impl.html", null ],
    [ "returns_void_impl&lt; F, void_t&lt; invoke_result_t&lt; F, U... &gt; &gt;, U... &gt;", "structnonstd_1_1detail_1_1returns__void__impl_3_01F_00_01void__t_3_01invoke__result__t_3_01F_00_899bbcae771d97efe99e3eeffbd178c6.html", null ],
    [ "optional_storage_base", "structnonstd_1_1detail_1_1optional__storage__base.html", "structnonstd_1_1detail_1_1optional__storage__base" ],
    [ "optional_storage_base&lt; T, true &gt;", "structnonstd_1_1detail_1_1optional__storage__base_3_01T_00_01true_01_4.html", "structnonstd_1_1detail_1_1optional__storage__base_3_01T_00_01true_01_4" ],
    [ "optional_operations_base", "structnonstd_1_1detail_1_1optional__operations__base.html", null ],
    [ "optional_copy_base", "structnonstd_1_1detail_1_1optional__copy__base.html", null ],
    [ "optional_copy_base&lt; T, false &gt;", "structnonstd_1_1detail_1_1optional__copy__base_3_01T_00_01false_01_4.html", null ],
    [ "optional_move_base", "structnonstd_1_1detail_1_1optional__move__base.html", null ],
    [ "optional_move_base&lt; T, false &gt;", "structnonstd_1_1detail_1_1optional__move__base_3_01T_00_01false_01_4.html", null ],
    [ "optional_copy_assign_base", "structnonstd_1_1detail_1_1optional__copy__assign__base.html", null ],
    [ "optional_copy_assign_base&lt; T, false &gt;", "structnonstd_1_1detail_1_1optional__copy__assign__base_3_01T_00_01false_01_4.html", null ],
    [ "optional_move_assign_base", "structnonstd_1_1detail_1_1optional__move__assign__base.html", null ],
    [ "optional_move_assign_base&lt; T, false &gt;", "structnonstd_1_1detail_1_1optional__move__assign__base_3_01T_00_01false_01_4.html", null ],
    [ "optional_delete_ctor_base", "structnonstd_1_1detail_1_1optional__delete__ctor__base.html", null ],
    [ "optional_delete_ctor_base&lt; T, true, false &gt;", "structnonstd_1_1detail_1_1optional__delete__ctor__base_3_01T_00_01true_00_01false_01_4.html", null ],
    [ "optional_delete_ctor_base&lt; T, false, true &gt;", "structnonstd_1_1detail_1_1optional__delete__ctor__base_3_01T_00_01false_00_01true_01_4.html", null ],
    [ "optional_delete_ctor_base&lt; T, false, false &gt;", "structnonstd_1_1detail_1_1optional__delete__ctor__base_3_01T_00_01false_00_01false_01_4.html", null ],
    [ "optional_delete_assign_base", "structnonstd_1_1detail_1_1optional__delete__assign__base.html", null ],
    [ "optional_delete_assign_base&lt; T, true, false &gt;", "structnonstd_1_1detail_1_1optional__delete__assign__base_3_01T_00_01true_00_01false_01_4.html", null ],
    [ "optional_delete_assign_base&lt; T, false, true &gt;", "structnonstd_1_1detail_1_1optional__delete__assign__base_3_01T_00_01false_00_01true_01_4.html", null ],
    [ "optional_delete_assign_base&lt; T, false, false &gt;", "structnonstd_1_1detail_1_1optional__delete__assign__base_3_01T_00_01false_00_01false_01_4.html", null ],
    [ "i_am_secret", "structnonstd_1_1detail_1_1i__am__secret.html", null ],
    [ "in_place_type_tag", "structnonstd_1_1detail_1_1in__place__type__tag.html", null ],
    [ "in_place_index_tag", "structnonstd_1_1detail_1_1in__place__index__tag.html", null ]
];